# Generated by Django 4.0.5 on 2022-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='out',
            name='dur',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='out',
            name='rep',
            field=models.IntegerField(default=1),
        ),
    ]
